<a href="https://colab.research.google.com/github/leducthanhkim2004/aio2024/blob/main/Homework_week2_module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Lightness Calculate the max and min for Rgb
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
img=mpimg.imread('/content/sample_data/dog.jpeg')
print(img)
max_rgb=np.max(img,axis=2)
min_rgb=np.min(img,axis=2)
gray_img_01= (max_rgb+min_rgb)/2
plt.imshow(gray_img_01)
gray_img_01 [0 , 0]

[[[118 134  71]
  [ 89 105  42]
  [ 82  98  35]
  ...
  [151 163 149]
  [151 163 149]
  [151 163 149]]

 [[119 135  72]
  [ 89 105  42]
  [ 83  99  36]
  ...
  [151 164 147]
  [151 163 149]
  [151 164 147]]

 [[119 135  72]
  [ 90 106  43]
  [ 83  99  36]
  ...
  [151 164 146]
  [150 163 146]
  [150 163 145]]

 ...

 [[145 155  94]
  [126 136  73]
  [119 132  62]
  ...
  [116 152  82]
  [113 149  79]
  [110 147  77]]

 [[138 148  87]
  [119 129  66]
  [112 125  56]
  ...
  [116 151  83]
  [113 148  80]
  [110 147  78]]

 [[136 146  85]
  [117 127  64]
  [109 122  53]
  ...
  [117 152  86]
  [114 149  83]
  [111 148  81]]]


102.5

In [ ]:
#based on average method
RedChannels=img[:,:,0]
GrayChannels = img[:,:,1]
BlueChannels=img[:,:,2]
averChannels=(RedChannels+GrayChannels+BlueChannels)/3
plt.imshow(averChannels)
averChannels[0 , 0]

22.333333333333332

In [ ]:
gray_img_03=0.21*RedChannels+0.72*GrayChannels+0.07*BlueChannels
gray_img_03[0,0]

126.22999999999999

In [ ]:
import pandas as pd
df =pd.read_csv('/content/sample_data/advertising.csv')
print(df)
data=df.to_numpy()
Sales=data[:,3]
print('max=', np.max(Sales))
print('index',np.argmax(Sales))
print('average', np.mean(data[:,0]))
count = np.count_nonzero(Sales >= 20)
print(count)
#len(x)
# Giả sử 'data' là mảng NumPy của bạn với cột 'Sales' ở chỉ số 3 và cột 'Radio' ở chỉ số 2
Sales = data[:, 3]
Radio = data[:, 2]

# Tìm các chỉ số nơi 'Sales' lớn hơn hoặc bằng 15
indices = np.where(Sales >= 15)

# Trích xuất các giá trị 'Radio' tương ứng
selected_radio = Radio[indices]

# Tính giá trị trung bình
average_radio = np.mean(selected_radio)

print(average_radio)

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]
max= 27.0
index 175
average 147.0425
40
33.09082568807339


In [ ]:
import numpy as np

# Giả sử 'data' là mảng NumPy của bạn với cột 'Sales' ở chỉ số 3
Sales = data[:, 3]

# Tính giá trị trung bình của cột 'Sales'
mean_sales = np.mean(Sales)

# Tạo mảng mới 'scores'
scores = np.empty(Sales.shape, dtype=object)

# Gán giá trị cho mảng 'scores'
scores[Sales > mean_sales] = 'Good'
scores[Sales < mean_sales] = 'Bad'
scores[Sales == mean_sales] = 'Average'
scores[7:10]


array(['Bad', 'Bad', 'Good'], dtype=object)

In [ ]:
import numpy as np

# Giả sử 'data' là mảng NumPy của bạn với cột 'Sales' ở chỉ số 3
Sales = data[:, 3]

# Tính giá trị trung bình của cột 'Sales'
mean_sales = np.mean(Sales)

# Tìm giá trị gần nhất với giá trị trung bình
nearest_value = Sales[np.argmin(np.abs(Sales - mean_sales))]

# Tạo mảng mới 'scores'
scores = np.empty(Sales.shape, dtype=object)

# Gán giá trị cho mảng 'scores'
scores[Sales > nearest_value] = 'Good'
scores[Sales < nearest_value] = 'Bad'
scores[Sales == nearest_value] = 'Average'

# In kết quả scores[7:10]
print(scores[7:10])

['Bad' 'Bad' 'Good']
