In [3]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
  def __init__(self):
    super().__init__() # Add missing parentheses after super
  def forward(self,x):
    x_max=torch.max(x,dim=0,keepdim=True)
    x_exp=torch.exp(x-x_max.values) # Change x_max.value to x_max.values
    partition=x_exp.sum(0,keepdims=True)
    return x_exp/partition

data=torch.tensor([1,2,3]) # Fix typo: tesnsor to tensor
softmax_table=MySoftmax() # Change SoftMaxStable to MySoftmax
output = softmax_table(data) # Call the softmax_table function with data
# Remove incomplete assert statement
print(output)


tensor([0.0900, 0.2447, 0.6652])


In [6]:
data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output

tensor([0., 0., 1.])

In [5]:
import torch
import torch . nn as nn

class SoftmaxStable ( nn . Module ):
  def __init__ ( self ) :
    super ().__init__ ()

  def forward ( self , x ) :
    #calculate based on  softmax table
    max_val=torch.max(x)
    exp_x=torch.exp(x-max_val)
    sum_exp_x=torch.sum(exp_x)
    return exp_x/sum_exp_x

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [10]:
from abc import ABC,abstractmethod
class Person(ABC):
  def __init__(self,name:str,yob:int):
    self._name=name
    self._yob=yob
  def get_yob(self):
    return self._yob
  @abstractmethod
  def describe(self):
    pass
class Student(Person):
  def __init__(self,name:str,yob:str,grade:str):
    super().__init__(name,yob)
    self._grade=grade
  def get_name(self):
    return self._name
  def describe(self):
        return f"Student Name: {self._name}, Year of Birth: {self._yob}, Grade: {self._grade}"

# Example usage
student = Student("John Doe", 2000, "A")
print(student.get_name())  # Output: John Doe
print(student.get_yob())   # Output: 2000
print(student.describe())

John Doe
2000
Student Name: John Doe, Year of Birth: 2000, Grade: A


In [14]:
class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        return f"Teacher Name: {self._name}, Year of Birth: {self._yob}, Subject: {self._subject}"

# Example usage
teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
assert teacher1._yob == 1991
print(teacher1.describe())  # Output: Teacher Name: teacherZ2023, Year of Birth: 1991, Subject: History


Teacher Name: teacherZ2023, Year of Birth: 1991, Subject: History


In [17]:
class Doctor(Person):
  def __init__(self,name:str,yob:int,specialist:str):
      super().__init__(name,yob)
      self._specialist=specialist
  def describe(self):
    return f"The Doctor Name:{self._name},Year of Birth{self._yob},Specialist:{self._specialist}"
doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1 . _yob == 1981
doctor1.describe ()


'The Doctor Name: doctorZ2023 ,Year of Birth1981,Specialist: Endocrinologists '

In [28]:
class Ward:
    def __init__(self, name):
        self._name = name
        self._list_people = list()

    def add_person(self, person: Person):
        self._list_people.append(person)

    def describe(self):
        print(f"Ward Name: {self._name}")
        for person in self._list_people:
            print(person.describe())

    def count_doctor(self):
        count = 0
        for person in self._list_people:
            if isinstance(person, Doctor):
                count += 1
        return count
    def sort_age(self):
        sorted_people = sorted(self._list_people, key=lambda x: x._yob)
        return [person.describe() for person in sorted_people]
    def averTeacher(self):
      sum=0
      count=0
      for person in self._list_people:
        if isinstance(person,Teacher):
          sum+=person._yob
          count+=1
      return sum/count
# Example usage
student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")

ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
print(ward1.sort_age())
print(ward1.averTeacher())
assert ward1.count_doctor() == 2

ward1.describe()

['The Doctor Name:doctorA,Year of Birth1945,Specialist:Endocrinologists', 'Teacher Name: teacherA, Year of Birth: 1969, Subject: Math', 'The Doctor Name:doctorB,Year of Birth1975,Specialist:Cardiologists', 'Teacher Name: teacherB, Year of Birth: 1995, Subject: History', 'Student Name: studentA, Year of Birth: 2010, Grade: 7']
1982.0
Ward Name: Ward1
Student Name: studentA, Year of Birth: 2010, Grade: 7
Teacher Name: teacherA, Year of Birth: 1969, Subject: Math
Teacher Name: teacherB, Year of Birth: 1995, Subject: History
The Doctor Name:doctorA,Year of Birth1945,Specialist:Endocrinologists
The Doctor Name:doctorB,Year of Birth1975,Specialist:Cardiologists


In [31]:
class MyStack :
  def __init__ ( self , capacity ) :
      self . __capacity = capacity
      self . __stack = []

  def is_full ( self ) :
        return len( self . __stack ) == self . __capacity

  def push ( self , value ) :
 ### Your Code Here
    if not self.is_full():
      self.__stack.append(value)
    else:
      raise Exception("Stack is full")
 ### End Code Here

  def top ( self ) :
 ### Your Code Here
    if self.__stack:
      return self.__stack[-1]
    else :
       raise Exception("Stack is empty")
 # End Code Here

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


In [36]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if not self.is_full():
            self.__queue.append(value)
        else:
            raise Exception("Queue is full")

    def dequeue(self):
        if self.__queue:
            return self.__queue.pop(0)
        else:
            raise Exception("Queue is empty")

    def front(self):
        if self.__queue:
            return self.__queue[0]
        else:
            raise Exception("Queue is empty")

# Example usage
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())  # Output: 1


1
