<a href="https://colab.research.google.com/github/leducthanhkim2004/aio2024/blob/main/Week4_module_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
def compute_mean(X):
  return 1/len(X)*np.sum(X)
X=[2 , 0 , 2 , 2 , 7, 4 , -2 , 5 , -1 , -1]
print(np.mean(X))
assert(compute_mean(X)==np.mean(X))

1.8


In [14]:
def compute_median(X):
  size= len(X)
  X=np.sort(X)
  print(X)
  if (size % 2 ==0):
    return (X[size//2]+X[size//2-1])/2
  else:
      return X[size//2]
X = [1 , 5 , 4 , 4 , 9, 13]
assert(compute_median(X)==np.median(X))
print("Median",compute_median(X))

[ 1  4  4  5  9 13]
[ 1  4  4  5  9 13]
Median 4.5


In [21]:
def compute_std_variance(X):
  mean =compute_mean(X)
  variance = 0
  sum_square = 0
  for element in X:
    sum_square += (element - mean)**2
  variance =sum_square/len(X)
  return variance, np.sqrt(variance)
X = [ 171 , 176 , 155 , 167 , 169 , 182]
print ( compute_std_variance( X )[1] )

8.32666399786453


In [44]:
import numpy as np

def compute_correlation_coefficient(X, Y):
    N = len(X)
    sum_X = np.sum(X)
    sum_Y = np.sum(Y)
    sum_XY = np.sum(X * Y)
    sum_X2 = np.sum(X ** 2)
    sum_Y2 = np.sum(Y ** 2)

    numerator = N * sum_XY - sum_X * sum_Y
    denominator = np.sqrt((N * sum_X2 - sum_X ** 2) * (N * sum_Y2 - sum_Y ** 2))

    return np.round(numerator / denominator, 2)

X = np.asarray([-2, -5, -11, 6, 4, 15, 9])
Y = np.asarray([4, 25, 121, 36, 16, 225, 81])
print("Correlation:", compute_correlation_coefficient(X, Y))


Correlation: 0.42


In [58]:
#!gdown --id 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
data =pd.read_csv("/content/advertising.csv")
def correlation(x,y):
  x_mean=compute_mean(x)
  y_mean=compute_mean(y)
  x_minus_x_mean= x -x_mean
  y_minus_y_mean =y-y_mean
  nominator = np.sum(x_minus_x_mean*y_minus_y_mean)
  denominator = np.sqrt(np.sum(x_minus_x_mean**2)*np.sum(y_minus_y_mean**2))
  return nominator /denominator
x = data ['TV']
y = data ['Radio']
corr_xy = correlation(x , y )
print ( f" Correlation between TV and Sales : { round ( corr_xy , 2)}")


 Correlation between TV and Sales : 0.05


In [72]:
import pandas as pd
import numpy as np

# Load the data
data = pd.read_csv("/content/advertising.csv")

def correlation(x, y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)

    x_minus_x_mean = x - x_mean
    y_minus_y_mean = y - y_mean

    nominator = np.sum(x_minus_x_mean * y_minus_y_mean)
    denominator = np.sqrt(np.sum(x_minus_x_mean ** 2) * np.sum(y_minus_y_mean ** 2))

    return np.round(nominator / denominator, 2)

features = ['TV', 'Radio', 'Newspaper']

for feature_1 in features:
    for feature_2 in features:
        correlation_value = correlation(data[feature_1], data[feature_2])
        print(f"Correlation between {feature_1} and {feature_2}: {correlation_value}")


Correlation between TV and TV: 1.0
Correlation between TV and Radio: 0.05
Correlation between TV and Newspaper: 0.06
Correlation between Radio and TV: 0.05
Correlation between Radio and Radio: 1.0
Correlation between Radio and Newspaper: 0.35
Correlation between Newspaper and TV: 0.06
Correlation between Newspaper and Radio: 0.35
Correlation between Newspaper and Newspaper: 1.0


In [75]:
x=data['Radio']
y=data['Newspaper']
print(np.corrcoef(x,y))

[[1.         0.05480866]
 [0.05480866 1.        ]]


In [77]:
data.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [105]:
#!gdown --id 1jh2p2DlaWsDo_vEWIcTrNh3mUuXd-cw6
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import  TfidfVectorizer
vi_data_df = pd . read_csv ("/content/vi_text_retrieval.csv")
context = vi_data_df ['text']
context = [ doc . lower () for doc in context ]
tfidf_vectorizer = TfidfVectorizer ()
context_embedded = tfidf_vectorizer.fit_transform (context)
context_embedded . toarray () [7][0]

0.31126580760710637

In [103]:
from sklearn.metrics.pairwise import cosine_similarity

def tfidf_search(question, tfidf_vectorizer, top_d=5):
    # Lowercasing before encoding
    question = [word.lower() for word in question.split()]

    # Transform the query into TF-IDF vector
    query_embedded = tfidf_vectorizer.transform([' '.join(question)])

    # Compute cosine similarity between the query and all documents
    cosine_scores = cosine_similarity(query_embedded, context_embedded).flatten()

    # Get top k cosine score and index its
    results = []
    for idx in cosine_scores.argsort()[-top_d:][::-1]:
        doc_score = {
            'cosine_score': cosine_scores[idx],
            'idx': idx
        }
        results.append(doc_score)

    return results

# Example usage
question = vi_data_df.iloc[0]['question']
results = tfidf_search(question, tfidf_vectorizer, top_d=5)

# Output the cosine score of the top result
print(results[0]['cosine_score'])


0.6279910475266974


In [104]:
from sklearn.metrics.pairwise import cosine_similarity

def corr_search(question, tfidf_vectorizer, top_d=5):
    # Lowercasing before encoding
    query_embedded = tfidf_vectorizer.transform([question.lower()])

    # Compute cosine similarity between the query and all documents
    corr_scores = cosine_similarity(query_embedded, context_embedded)

    # Flatten the array and remove self-correlation
    corr_scores = corr_scores.flatten()

    # Get top k correlation score and index its
    results = []
    for idx in corr_scores.argsort()[-top_d:][::-1]:
        doc = {
            'id': idx,
            'corr_score': corr_scores[idx]
        }
        results.append(doc)

    return results

# Example usage
question = vi_data_df.iloc[0]['question']
results = corr_search(question, tfidf_vectorizer, top_d=5)

# Output the correlation score of the second top result
print(results[1]['corr_score'])


0.2114579586225163
